<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <RootNamespace>English.Service</RootNamespace>
    <AssemblyName>English.Service</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\English.Entity\English.Entity.csproj" />
  </ItemGroup>

</Project>
