// <auto-generated />
using System;
using English.Repository.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace English.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("EnglishLocker.Models.Entities.AppConfiguration", b =>
                {
                    b.Property<string>("ConfigKey")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigValue")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("ConfigKey");

                    b.ToTable("AppConfigurations", (string)null);
                });

            modelBuilder.Entity("EnglishLocker.Models.Entities.Deck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Decks", (string)null);
                });

            modelBuilder.Entity("EnglishLocker.Models.Entities.EmergencyLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BypassedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeducted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EmergencyLogs", (string)null);
                });

            modelBuilder.Entity("EnglishLocker.Models.Entities.LearningMaterial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoryType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContextTag")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeckId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExampleSentence")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("Meaning")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phonetics")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeckId");

                    b.ToTable("LearningMaterials", (string)null);
                });

            modelBuilder.Entity("EnglishLocker.Models.Entities.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AudioLocalPath")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageLocalPath")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LearningMaterialId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OptionsPayload")
                        .HasColumnType("TEXT");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<int>("TestType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LearningMaterialId");

                    b.ToTable("Questions", (string)null);
                });

            modelBuilder.Entity("EnglishLocker.Models.Entities.StudyHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ResponseTimeMs")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TestedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("StudyHistories", (string)null);
                });

            modelBuilder.Entity("EnglishLocker.Models.Entities.StudyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("EasinessFactor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(2.5);

                    b.Property<double>("Interval")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("LastTestedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NextReviewTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("RepetitionCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId")
                        .IsUnique();

                    b.ToTable("StudyRecords", (string)null);
                });

            modelBuilder.Entity("EnglishLocker.Models.Entities.LearningMaterial", b =>
                {
                    b.HasOne("EnglishLocker.Models.Entities.Deck", "Deck")
                        .WithMany("LearningMaterials")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deck");
                });

            modelBuilder.Entity("EnglishLocker.Models.Entities.Question", b =>
                {
                    b.HasOne("EnglishLocker.Models.Entities.LearningMaterial", "LearningMaterial")
                        .WithMany("Questions")
                        .HasForeignKey("LearningMaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LearningMaterial");
                });

            modelBuilder.Entity("EnglishLocker.Models.Entities.StudyHistory", b =>
                {
                    b.HasOne("EnglishLocker.Models.Entities.Question", "Question")
                        .WithMany("StudyHistories")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("EnglishLocker.Models.Entities.StudyRecord", b =>
                {
                    b.HasOne("EnglishLocker.Models.Entities.Question", "Question")
                        .WithOne("StudyRecord")
                        .HasForeignKey("EnglishLocker.Models.Entities.StudyRecord", "QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("EnglishLocker.Models.Entities.Deck", b =>
                {
                    b.Navigation("LearningMaterials");
                });

            modelBuilder.Entity("EnglishLocker.Models.Entities.LearningMaterial", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("EnglishLocker.Models.Entities.Question", b =>
                {
                    b.Navigation("StudyHistories");

                    b.Navigation("StudyRecord");
                });
#pragma warning restore 612, 618
        }
    }
}
