<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>English.Entity</RootNamespace>
    <AssemblyName>English.Entity</AssemblyName>
  </PropertyGroup>

</Project>
