<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <RootNamespace>English.ViewModel</RootNamespace>
    <AssemblyName>English.ViewModel</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\English.Entity\English.Entity.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.3.2" />
  </ItemGroup>

</Project>
